sudo: false
notifications:
  email:
    on_success: change
    on_failure: change
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - ruby-head
  - jruby-9.1.5.0
