---
version: "{build}"
clone_depth: 1
environment:
  matrix:
    - RUBY_VERSION: 22
    - RUBY_VERSION: 23
install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - bundle install --without development
build: off
test_script:
  - bundle exec rake
